apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpaHViZy5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiaWh1YmciLCJwYXNzd29yZCI6ImlCRWhYVmk4VW85czRwVlY4bFBkTEJQUExSdTVpNCtmNlE5VUFBUzZPcCtBQ1JDUExBMW0iLCJlbWFpbCI6ImluZm9AaWh1YmcudGVjaCJ9fX0=

