apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-dev
  template:
    metadata:
      labels:
        app: dashboard-dev
    spec:
      containers:
      - name: dashboard
        image: ihubg.azurecr.io/crm-dashboard-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API
          valueFrom:
            secretKeyRef:
              name: secrets-dashboard-dev
              key: REACT_APP_API
        resources:  # Agrega esta sección para definir límites y solicitudes de recursos
          requests:
            memory: "256Mi"   # Ajusta según la necesidad real de la aplicación
            cpu: "200m"       # Ajusta según la necesidad real de la aplicación
          limits:
            memory: "512Mi"   # Ajusta según la necesidad real de la aplicación
            cpu: "500m"       # Ajusta según la necesidad real de la aplicación
      imagePullSecrets:
      - name: acr-secret
