apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: ihubg.azurecr.io/crm-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API
          valueFrom:
            secretKeyRef:
              name: secrets-dashboard
              key: REACT_APP_API
      imagePullSecrets:
      - name: acr-secret
      